//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson7.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course : BaseEntity
    {
        public Course()
        {
            this.Students = new HashSet<Student>();
            this.StudentNotas = new HashSet<StudentNota>();
        }
    
        public int Id { get; set; }
        public string Numer { get; set; }
        public string Emer { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<StudentNota> StudentNotas { get; set; }
    }
}
