//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson7.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Lesson7Entities : DbContext, IContext
    {
        public Lesson7Entities()
            : base("name=Lesson7Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual IDbSet<Course> Courses { get; set; }
        public virtual IDbSet<Student> Students { get; set; }
        public virtual IDbSet<StudentNota> StudentNotas { get; set; }
    }
}
