//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentType
    {
        public StudentType()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public string Tipi { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
