//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class View1Studentet
    {
        public string FullName { get; set; }
        public string Kursi { get; set; }
        public string NumriIKursit { get; set; }
        public int Id { get; set; }
    }
}
